# Igual que la configuración por defecto de nginx, pero escuchando también en el 3000.
server {
    listen 80;
    listen 3000;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
